apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-cxsd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/susdas_quay_org/mvp-dev-cucg-tenant/mvp-test-app/test-mvp-component-cxsd@sha256:bd8883411bdfe7db84e780e80d484b60a23a61e53be43c0f62b9929f0764b165
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
